### ISSUE TITLE
Best way to parse data?

### ISSUE THREAD

**Issue by ayzaan** [bksim/wikisurf#1]
Right now we use mediawiki API

Is there any way the 500 link limit is going to be an issue?

Would there be any advantage in having information like the "importance" of a link? For example, in a wikipedia article there are subheadings that sometimes have a link below them that points to a "Main article". What if on our graphs, we had the "Main article" nodes that branch off be bigger? Scraping directly from the site would allow us to get this information.

**Comment by bksim** [comment]
Yeah, I was worried about the 500 link limit also (i think there's a comment in there)...we can definitely scrape directly from the site also, I was just worried it might take a lot longer (especially given how many pages there are).

I was thinking that the size of the nodes (based on importance) would be determined by some graph theoretic measure, such as how pages that new node is linked to by (pagerank-esque), but I suppose we could do it by what section the link is in too? Not sure what the best way to do this is.

Are there a lot of pages with more than 500 links?

From the looks of the graph (http://people.seas.harvard.edu/~amiloslavov/images/pop3.jpg) from http://people.seas.harvard.edu/~amiloslavov/structure.html, it looks as if 500 is a good upper limit in general?

**Comment by ayzaan** [comment]
True, it's probably better to do it with some graph theory.

Yeah looks like 500 links is actually alot, so should be good. Check out my branch I edited your file a bit for some functions for creating/parsing graphs.

**Comment by bksim** [comment]
Nice! I saw it. Can we run python on web servers?
