### ISSUE TITLE
converting to json

### ISSUE THREAD

**Issue by bksim** [bksim/wikisurf#2]
Your converting to json method in the python method only works for depth 1 right?

**Comment by ayzaan** [comment]
Did it not work with depth 2? I never tested it, i'm trying to test it right now but my connection keeps timing out. I'm pretty sure it should work though.

**Comment by bksim** [comment]
Is G[node] a dictionary of all nodes that that node is connected to? If so, then it works, my fault.

**Comment by ayzaan** [comment]
Yeah, that's what it does.

**Comment by bksim** [comment]
Got it!
