### ISSUE TITLE
randomizing displayed nodes

### ISSUE THREAD

**Issue by bksim** [bksim/wikisurf#3]
How should we do this? Has to be dynamic. Call another function in another file via ajax to return a subset of the total JSON? Or do locally in js?

**Comment by ayzaan** [comment]
We could start start using a web framework. Our JS could submit the user query and load it from the server, and the server could handle the randomization. Maybe flask? It's a lot more lightweight that Django, seems good for our purposes though.

Another option is to have all of the total JSON loaded locally, and then randomize locally and change the visible nodes based on user interaction (I feel like there should be an option to display other nodes, if the user drags the graph maybe other nodes start appearing?). I think this approach would be faster cause it wouldn't have to load from the server for every change in the graph. Either way, I think it'd help if we had a web framework set up.

**Comment by bksim** [comment]
I agree. There's a variety of 'light' frameworks out there - flask, sinatra (ruby), etc. I don't know much about any of them, so whichever you like should be good.

**Comment by ayzaan** [comment]
Yeah, let's try flask since our stuff is already in python. I'll get it set up sometime today.

**Comment by bksim** [comment]
Sweet, sounds good. How do you set it up, is it something you have to install on server? Or does it just generate html?

**Comment by bksim** [comment]
(ie would we run it on heroku?)

**Comment by ayzaan** [comment]
Runs the same way Django runs. Yeah we could run it on heroku. We could test locally on localhost and then run production version on heroku.

**Comment by bksim** [comment]
Sweet. Sounds good - let me know when you have it set up! Can we merge it into github?

**Comment by ayzaan** [comment]
Alright I set up flask. Just install Flask on your computer (probably better to do it in a virtualenv). 

```
pip install Flask
```

then just run

```
python site/wikisurf.py
```

and navigate to 

```
localhost:5000
```

Haha this github markdown is fun!

**Comment by bksim** [comment]
nice! i'll try it later tonight or tomorrow, gotta pack.
