### ISSUE TITLE
Main.js json loading still does not work

### ISSUE THREAD

**Issue by ayzaan** [bksim/wikisurf#6]
I tried playing around with it a little bit. My javascript skills are not great though.

**Comment by ayzaan** [comment]
I got the jQuery to work and it loads the json. Right now it's using the Computer article so it looks very cluttered obviously. A few things I discovered. Look in the main.js code, we only need the "edges" JSON info and no separate info for "nodes". So all the info we need is mappings like:

```
var graph = {edges: g_edges}
sys.graft(graph)
```

where `g_edges` is something like:

```
{"Computer":{"32-bit":{},"Ada (programming language)":{},"ARPANET":{},"1890 United States Census":{},"Abacus":{},"Aberdeen Proving Ground":{},"86-DOS":{},"3D computer graphics":{},"Accounting software":{},"3D computer graphics software":{},"ARM architecture":{},"8-bit":{},"16-bit":{},"64-bit":{},"4-bit":{}}} 
```

And that's ALL the info we need to generate a graph in arbor.js.

**Comment by ayzaan** [comment]
@bksim I pushed the changes to brandon-return-json, check it out it should be working. To avoid clutter in the graph I also used another (smaller) random article instead of Computer.

**Comment by bksim** [comment]
Regarding first comment: Yup, arbor.js automatically creates nodes when edges are created between nodes that don't yet exist. The reason I made nodes explicitly is because this allowed us to specify attributes (ie the dictionary containing info like 'link') which might be useful later when we need to figure out behavior upon click or what not.

**Comment by bksim** [comment]
How did you get it to not complain about the cross domain request?

**Comment by ayzaan** [comment]
Oh makes sense. Then a problem we'll have when randomizing is getting a random number of nodes, and then getting the SAME corresponding edges. For the cross domain request I added a module in flask that handles csrf related things, seems to be working. Works for you right?

**Comment by bksim** [comment]
Yup it works. Had to pip install flask-csrf. To solve the random part, we could choose random edges. And all the nodes they're attached to.
